name: Terraform Manual Deployment

on:
  workflow_dispatch:
    inputs:
      terraform-version:
        description: "Terraform Version"
        required: true
        default: "1.8.0"

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          pwd
          ls -la
          find . -type d

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs['terraform-version'] }}

      - name: Terraform Init
        working-directory: terraform/terraform/environments/dev
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: terraform/terraform/environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: terraform/terraform/environments/dev
        run: terraform validate
