name: Terraform Manual Deployment

on:
  workflow_dispatch:
    inputs:
      terraform-version:
        description: "Terraform Version"
        required: true
        default: "1.8.0"

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ github.event.inputs['terraform-version'] }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify AWS Access
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate
